org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20,)
forge_version=47.3.0
forge_version_range=[47.3,)
loader_version_range=[47,)

## Mod Properties
mod_id=createqol
mod_name=Create Quality of Life
mod_license=MIT
mod_version=1.3.0
mod_group_id=fr.iglee42
mod_authors=iglee42
mod_description=Enjoy lots of little tweaks on Create !

## Items Viewers
jei_version=15.20.0.106
rei_version=12.0.652
cloth_config_version=11.1.106
architectury_version=9.1.12

## Create
create_version = 6.0.0-4
create_version_range = [6.0.1,)
ponder_version = 1.0.38
flywheel_version = 1.0.0-217
registrate_version = MC1.20-1.3.3

## Other Dependencies
chipped_version=3.0.7
rflib_version=2.1.29



